/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clave_dicotomica;

import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.*;

/**
 *
 * @author Naim
 */
public class InterfazPrincipal extends javax.swing.JFrame 
{
    ArbolABB arbolArbolesTemplados;
    ArbolABB arbolFamiliasBotanicas;
    
    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() 
    {
        this.arbolArbolesTemplados = null;
        this.arbolFamiliasBotanicas = null;
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        // Eliminar las dos pestañas que aún no han sido cargadas
        this.panel_principal.remove(1);
        this.panel_principal.remove(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JTabbedPane();
        panel_menu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cargar_clave_button = new javax.swing.JButton();
        panel_arboles_templados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        busqueda_arboles_templados_btn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        resultado_arboles_templados_scpn = new javax.swing.JScrollPane();
        resultado_arboles_templados = new javax.swing.JTextArea();
        panel_familias_botanicas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        busqueda_familia_botanica_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        resultado_familia_botanica_scpn = new javax.swing.JScrollPane();
        resultado_familia_botanica = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_principal.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Identificar plantas");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Para empezar a identificar plantas, debes cargar alguno de los dos tipos de \nclaves dicotómicas: árboles templados o familias botánicas. \nLas opciones se habilitaran en las pestañas de arriba al cargar alguna de las dos claves.\n");
        jScrollPane1.setViewportView(jTextArea1);

        cargar_clave_button.setText("Cargar clave dicotómica");
        cargar_clave_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_clave_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menuLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(cargar_clave_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargar_clave_button)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        panel_principal.addTab("Principal", panel_menu);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Encontrar árboles templados");

        busqueda_arboles_templados_btn.setText("Empezar búsqueda");
        busqueda_arboles_templados_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_arboles_templados_btnActionPerformed(evt);
            }
        });

        jLabel5.setText("Resultado:");

        resultado_arboles_templados.setEditable(false);
        resultado_arboles_templados.setColumns(20);
        resultado_arboles_templados.setRows(5);
        resultado_arboles_templados_scpn.setViewportView(resultado_arboles_templados);

        javax.swing.GroupLayout panel_arboles_templadosLayout = new javax.swing.GroupLayout(panel_arboles_templados);
        panel_arboles_templados.setLayout(panel_arboles_templadosLayout);
        panel_arboles_templadosLayout.setHorizontalGroup(
            panel_arboles_templadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_arboles_templadosLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(busqueda_arboles_templados_btn)
                .addGap(224, 224, 224))
            .addGroup(panel_arboles_templadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_arboles_templadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(panel_arboles_templadosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(resultado_arboles_templados_scpn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panel_arboles_templadosLayout.setVerticalGroup(
            panel_arboles_templadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_arboles_templadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busqueda_arboles_templados_btn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado_arboles_templados_scpn, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_principal.addTab("Árboles templados", panel_arboles_templados);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Encontrar familia botánica");

        busqueda_familia_botanica_btn.setText("Empezar búsqueda");
        busqueda_familia_botanica_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_familia_botanica_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultado:");

        resultado_familia_botanica.setEditable(false);
        resultado_familia_botanica.setColumns(20);
        resultado_familia_botanica.setRows(5);
        resultado_familia_botanica_scpn.setViewportView(resultado_familia_botanica);

        javax.swing.GroupLayout panel_familias_botanicasLayout = new javax.swing.GroupLayout(panel_familias_botanicas);
        panel_familias_botanicas.setLayout(panel_familias_botanicasLayout);
        panel_familias_botanicasLayout.setHorizontalGroup(
            panel_familias_botanicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_familias_botanicasLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(busqueda_familia_botanica_btn)
                .addGap(224, 224, 224))
            .addGroup(panel_familias_botanicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_familias_botanicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panel_familias_botanicasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(resultado_familia_botanica_scpn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panel_familias_botanicasLayout.setVerticalGroup(
            panel_familias_botanicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_familias_botanicasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busqueda_familia_botanica_btn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado_familia_botanica_scpn, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_principal.addTab("Familias botánicas", panel_familias_botanicas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargar_clave_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_clave_buttonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileFilter(new FileNameExtensionFilter("Archivo JSON", "json"));
        
        int retval = chooser.showOpenDialog(this);
        if(retval == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                FileReader reader = new FileReader(chooser.getSelectedFile());
                JSONObject jsonObject = new JSONObject(new JSONTokener(reader));
                
                if(jsonObject.has("Arboles templados"))
                {
                    if(this.arbolArbolesTemplados == null)
                    {
                        this.panel_principal.addTab("Arboles templados", panel_arboles_templados);
                    }
                    this.arbolArbolesTemplados = ArbolABB.cargarDeJSON(jsonObject.getJSONArray("Arboles templados"));
                }
                else if(jsonObject.has("Familias botánicas"))
                {
                    if(this.arbolFamiliasBotanicas == null)
                    {
                        this.panel_principal.addTab("Familias botánicas", panel_familias_botanicas);
                    }
                    this.arbolFamiliasBotanicas = ArbolABB.cargarDeJSON(jsonObject.getJSONArray("Familias botánicas"));
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "La clave dicotómica es inválida.", "Error de carga de archivo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            catch(FileNotFoundException | JSONException e)
            {
                JOptionPane.showMessageDialog(this, "No se pudo cargar el archivo seleccionado.", "Error de carga de archivo", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_cargar_clave_buttonActionPerformed

    private void busqueda_arboles_templados_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_arboles_templados_btnActionPerformed
        String res = this.arbolArbolesTemplados.determinarEspecie(this.arbolArbolesTemplados.getRoot());
        this.resultado_arboles_templados.setText(res);
    }//GEN-LAST:event_busqueda_arboles_templados_btnActionPerformed

    private void busqueda_familia_botanica_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_familia_botanica_btnActionPerformed
        String res = this.arbolFamiliasBotanicas.determinarEspecie(this.arbolFamiliasBotanicas.getRoot());
        this.resultado_familia_botanica.setText(res);
    }//GEN-LAST:event_busqueda_familia_botanica_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busqueda_arboles_templados_btn;
    private javax.swing.JButton busqueda_familia_botanica_btn;
    private javax.swing.JButton cargar_clave_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panel_arboles_templados;
    private javax.swing.JPanel panel_familias_botanicas;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JTabbedPane panel_principal;
    private javax.swing.JTextArea resultado_arboles_templados;
    private javax.swing.JScrollPane resultado_arboles_templados_scpn;
    private javax.swing.JTextArea resultado_familia_botanica;
    private javax.swing.JScrollPane resultado_familia_botanica_scpn;
    // End of variables declaration//GEN-END:variables
}
